development:
  access_key_id: AKIAJUFMTVFS7EEOU3XA
  secret_access_key: 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
  bucket: crossingmusic_dev
test:
  access_key_id: AKIAJUFMTVFS7EEOU3XA
  secret_access_key: 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
  bucket: crossingmusic_test
production:
  access_key_id: AKIAJUFMTVFS7EEOU3XA
  secret_access_key: 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
  bucket: crossingmusic_prod